# Generated by Django 5.0.8 on 2024-10-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=1, max_length=5, verbose_name='Discount (%)'),
            preserve_default=False,
        ),
    ]
