# Generated by Django 5.0.8 on 2024-10-04 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hover_image',
            field=models.ImageField(default=1, upload_to='product/hover_image/', verbose_name='Hover Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, max_length=5, null=True, verbose_name='Discount (%)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='products.product', verbose_name='Product'),
        ),
    ]
