# Generated by Django 5.0.8 on 2024-10-04 10:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_hover_image_alter_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Body'),
        ),
    ]
