# Generated by Django 5.0.8 on 2024-10-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_advertising_body_alter_banner_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servises',
            name='icon',
            field=models.FileField(upload_to='servises_icon/', verbose_name='Servises_icon'),
        ),
    ]
