# Generated by Django 5.0.8 on 2024-10-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_servises_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hover_image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='hover_image',
            field=models.ImageField(default=1, upload_to='product/hover_image/', verbose_name='Hover Image'),
            preserve_default=False,
        ),
    ]
