# Generated by Django 5.0.6 on 2024-11-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_hover_image_productimage_hover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Sales count'),
        ),
    ]
